In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [32]:
v = np.array([[0,0,1,1], [1,0,0,0],[0,1,1,0],[0,0,0,1]])
a = 0.5;
w = np.array([[0.2,0.9],[0.4,0.7],[0.6,0.5],[0.8,0.3]])
print('v=',v)
print('****-------****')
print('w=',w)


v= [[0 0 1 1]
 [1 0 0 0]
 [0 1 1 0]
 [0 0 0 1]]
****-------****
w= [[0.2 0.9]
 [0.4 0.7]
 [0.6 0.5]
 [0.8 0.3]]


In [33]:
def eucd(n):
    d1=0
    d2=0
    for j in range(0,4):
        d1+=(w[j][0]-v[n][j])**2
        d2+=(w[j][1]-v[n][j])**2
    print('D1={0},D2={1}'.format(d1,d2))
    if d1<d2:
        b=0
    else:
        b=1
    for i in range(0,4):
        w[i][b]=w[i][b]+a*(v[n][i]-w[i][b])
    print(np.matrix(w))

In [34]:
eucd(0)

D1=0.4000000000000001,D2=2.04
[[0.1 0.9]
 [0.2 0.7]
 [0.8 0.5]
 [0.9 0.3]]


In [35]:
eucd(1)

D1=2.3000000000000003,D2=0.84
[[0.1  0.95]
 [0.2  0.35]
 [0.8  0.25]
 [0.9  0.15]]


In [36]:
eucd(2)

D1=1.5000000000000002,D2=1.91
[[0.05 0.95]
 [0.6  0.35]
 [0.9  0.25]
 [0.45 0.15]]


In [37]:
eucd(3)

D1=1.475,D2=1.8099999999999998
[[0.025 0.95 ]
 [0.3   0.35 ]
 [0.45  0.25 ]
 [0.725 0.15 ]]
